### ISSUE TITLE
import ss-validate pacakge

### ISSUE THREAD

**Issue by zqsha** [EBISPOT/gwas-sumstats-validator#13]
Hi there,

I installed the ss-validate package, but when I use "import ss-validate" it showed

import ss-validate
  File "<stdin>", line 1
    import ss-validate
                  ^
SyntaxError: invalid syntax

Is it because of incorrect package name?

Thanks,
cain

**Comment by jdhayhurst** [comment]
Hi yes, the correct import statement is:
```
import validate
```
I think the syntax error is because '-' is not allowable.
