### ISSUE TITLE
Validator fails when numerical values are smaller than the system limits

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-sumstats-validator#15]
values such as 3.44e-4084 are so small that they fail validation where numbers must be between 0 and 1. This mostly affects p-values. There are 3 obvious solutions to enable such values:
1) we adopt the -log10 approach - this would impact upon other parts of the process e.g. sumstats db
2) we accept pvalues of 0 
3) we mandate that pvaluesare provided in scientific notation - then we can treat as strings and split into mantissa and exponent and validate those parts as numbers.

**Comment by ljwh2** [comment]
Note from discussion: solution 2 would be easiest to implement. Is there is a reason why we need pvalues of zero to fail? In the short term we can probably handle these on a case-by-case basis

**Comment by jdhayhurst** [comment]
@ljwh2 If zero is acceptable is 1 also acceptable? If so, I will make it so pvalue can be  `0 <= p <= 1`. It is currently `0 < p < 1`.

**Comment by jdhayhurst** [comment]
Investigate: read in as str, validate as number but if it fails, split mantissa from exponent and validate the exponent.

**Comment by jdhayhurst** [comment]
The requirement until the working group has made a decision on this is that small p-values should pass, zero p-values should pass, but a warning should be raised so that the user knows that there are zero p-values (these may require investigation, but they will in fact pass)

**Comment by jdhayhurst** [comment]
just to confirm - true 0 and 1 p-values should not be permitted
