### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by alexxue81** [EBISPOT/gwas-sumstats-validator#18]
To whom it may concern,

I tried to install ss-validate by "pip install ss-validate", but got the following error:

```
Collecting ss-validate
  Downloading https://files.pythonhosted.org/packages/cb/e4/215150389797af9c901027cf8ef4e258ab0bd46202fac1fc1a1636ad8d08/ss-validate-0.3.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wnfsKo/ss-validate/setup.py", line 6, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wnfsKo/ss-validate/
```

Do you happen to know how to solve this problem? Thank you!

Cheers,
Angli

**Comment by jdhayhurst** [comment]
Hi @alexxue81.

What version of python and pip do you have installed?
This requires python3 and therefore pip3

**Comment by alexxue81** [comment]
> Hi @alexxue81.
> 
> What version of python and pip do you have installed?
> This requires python3 and therefore pip3

Thanks for your reply.

I changed to python3 and pip3 did the job. Thank you!
