### ISSUE TITLE
Add minimum number of SNPs to validator

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/gwas-sumstats-validator#8]
We need to add a minimum SNP number to the validator, since we had several submissions of very small numbers of SNPs.  

Sumstats files with fewer than 100K variants should fail validation, and return the following error message:

Error message: (ERROR):File contains fewer than 100,000 rows. If you have fewer than 100,000 variants in your dataset, please contact gwas-subs@ebi.ac.uk for further advice.

**Comment by ljwh2** [comment]
Just adding this here for background. There are arguments for and against SNPn thresholds - if we set it at 100K SNPs, according to our stated inclusion criteria (https://www.ebi.ac.uk/gwas/docs/methods/summary-statistics), we remove the possibility of accepting 23&Me data (where only top 10K SNPs are made available) or targeted array data where the post QC SNPn is <100K. However, if we go with a low threshold, this may encourage partial submissions. For now we should go with the stated inclusion criteria and will exceptions on an individual basis. We can review following outcome of working group discussions.

**Comment by ljwh2** [comment]
Open to suggestions on wording of error message

**Comment by jdhayhurst** [comment]
- minimum row feature added to validator (can be specified as cmd line arg if needed)
- added granularity to submission app error reporting to report on file extensions, headers, number of rows, file squareness or general data errors.

**Comment by ljwh2** [comment]
@buniello please test

**Comment by buniello** [comment]
1) step 1 of the test ok - offline validator @ljwh2 @jdhayhurst 
buniello-ml:~ buniello$ ss-validate -f /Users/buniello/Downloads/sumstats33k_test.tsv 
(INFO): Validating file extension...
(INFO): ok
(INFO): Validating headers...
(INFO): ok
(INFO): Validating file for squareness...
(INFO): ok
(INFO): Validating rows...
(ERROR): There are only 33656 rows detected in the file, but the minimum requirement is 100000
(INFO): File is invalid
(INFO): File contains too few rows..exiting before any further checks

**Comment by buniello** [comment]
2. Testing submission of 33k SNP file in sandbox -- ok @ljwh2 @jdhayhurst 
<img width="1080" alt="Screenshot 2020-08-26 at 14 48 08" src="https://user-images.githubusercontent.com/30833755/91311832-71081380-e7ab-11ea-8f4f-888e047054a0.png">
